name: Validate Pull Request

on:
  pull_request:

jobs:
  pull-request:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 17.3
        msbuild-architecture: x64

    # Before building, restore Nuget packages and install dependencies.
    - name: Install Dependencies
      run: |
        nuget restore source/SharpGL/SharpGL.sln
        ./source/SharpGL/config.ps1

    # Use our own build script as it hides some unneeded warnings.
    - name: Build
      run: |
        ./source/SharpGL/build.ps1
        ./source/SharpGL/pack.ps1

    # Test and upload coverage reports.
    - name: Test
      run: |
        ./source/SharpGL/test.ps1
        ./source/SharpGL/coverage.ps1

    # Upload the artifacts folder.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          ./source/SharpGL/artifacts/
